targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  sqlite_orm_generator:
    import: "package:sqlite_orm/generators/sqlite_orm_generator.dart"
    builder_factories: ["getSqlOrmGenerator"]
    build_extensions: { ".dart": ["g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]